name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart run tool/validate_repository.dart
      - run: |
          dart format lib/src/providers/web/site_specific_helpers.dart
          echo '---FORMAT DIFF---'
          git diff -- lib/src/providers/web/site_specific_helpers.dart
          exit 1
      - run: dart analyze
      - run: dart test
